.phony: run example test rund exampled

run:
	python sol.py input.txt

rund:
	python sol.py input.txt -d

example:
	python sol.py example.txt

exampled:
	python sol.py example.txt -d

test:
	pytest sol.py
