.phony: run example rund exampled example2 example2d

run:
	python sol.py -i input.txt

rund:
	python sol.py -i input.txt -d

example:
	python sol.py -i example.txt

exampled:
	python sol.py -i example.txt -d

example2:
	python sol.py -i example2.txt

example2d:
	python sol.py -i example2.txt -d
