.phony: run rund example exampled

run:
	python sol.py -i input.txt
	python sol2.py -i input.txt

rund:
	python sol.py -i input.txt -d
	python sol2.py -i input.txt -d

example:
	python sol.py -i example.txt
	python sol2.py -i example.txt

exampled:
	python sol.py -i example.txt -d
	python sol2.py -i example.txt -d
